# Search Algorithms
## Graph 3

### Creating the Adjacency Matrix based on the given graph

In [1]:
import numpy as np

vertices = ['S', 'A', 'B', 'C', 'D', 'G']

edges = [
    ('S', 'A', 1),
    ('A', 'B', 3),
    ('B', 'C', 1),
    ('B', 'G', 1),
    ('C', 'G', 1),
    ('D', 'G', 1)
]


num_vertices = len(vertices)
adjacency_matrix = np.zeros((num_vertices, num_vertices), dtype=int)


vertex_indices = {vertex: index for index, vertex in enumerate(vertices)}

for edge in edges:
    source, target, weight = edge
    source_index = vertex_indices[source]
    target_index = vertex_indices[target]
    adjacency_matrix[source_index][target_index] = weight


for row in adjacency_matrix:
    print(row)


[0 1 0 0 0 0]
[0 0 3 0 0 0]
[0 0 0 1 0 1]
[0 0 0 0 0 1]
[0 0 0 0 0 1]
[0 0 0 0 0 0]


### Depth First Search

In [2]:

def dfs(graph, start, goal, path=[]):
    path = path + [start]

    if start == goal:
        return path

    for vertex in range(len(graph[start])):
        if graph[start][vertex] > 0 and vertex not in path:
            new_path = dfs(graph, vertex, goal, path)
            if new_path:
                return new_path

    return None


goal_vertex = 'G'


start_vertex = vertices.index('S')
path = dfs(adjacency_matrix, start_vertex, vertices.index(goal_vertex))

if path is not None:
    path = [vertices[i] for i in path]
    print("Path from 'S' to 'G' found by DFS:", " -> ".join(path))
else:
    print("No path from 'S' to 'G' found by DFS")


Path from 'S' to 'G' found by DFS: S -> A -> B -> C -> G


### Brtish Museum Search

In [9]:
from collections import deque
def bms(graph, start, goal):
    visited = set()
    queue = [[start]]

    if start == goal:
        return [start]

    while queue:
        path = queue.pop(0)
        node = path[-1]

        if node not in visited:
            neighbors = [i for i, value in enumerate(graph[node]) if value > 0]

            for neighbor in neighbors:
                new_path = list(path)
                new_path.append(neighbor)
                queue.append(new_path)

                if neighbor == goal:
                    return new_path

            visited.add(node)

    return None


goal_vertex = 'G'


start_vertex = vertices.index('S')
path_indices = bms(adjacency_matrix, start_vertex, vertices.index(goal_vertex))

if path_indices is not None:
    path = [vertices[i] for i in path_indices]
    print("Path from 'S' to 'G' found by BMS:", " -> ".join(path))
else:
    print("No path from 'S' to 'G' found by BMS")


Path from 'S' to 'G' found by BMS: S -> A -> B -> G


### Breadth First Search

In [6]:
from collections import deque
def bfs(graph, start, goal):
    visited = set()
    queue = deque([[start]])

    if start == goal:
        return [start]

    while queue:
        path = queue.popleft()
        node = path[-1]

        if node not in visited:
            neighbors = [i for i, value in enumerate(graph[node]) if value > 0]

            for neighbor in neighbors:
                new_path = list(path)
                new_path.append(neighbor)
                queue.append(new_path)

                if neighbor == goal:
                    return new_path

            visited.add(node)

    return None


goal_vertex = 'G'

start_vertex = vertices.index('S')
path_indices = bfs(adjacency_matrix, start_vertex, vertices.index(goal_vertex))

if path_indices is not None:

    path = [vertices[i] for i in path_indices]
    print("Path from 'S' to 'G' found by BFS:", " -> ".join(path))
else:
    print("No path from 'S' to 'G' found by BFS")


Path from 'S' to 'G' found by BFS: S -> A -> B -> G


### Beam Search

In [11]:
def beam_search(graph, start, goal, beam_width):
    current_beam = [(start, [])]  

    while current_beam:
        next_beam = []

        for vertex, path in current_beam:
            neighbors = [i for i, value in enumerate(graph[vertex]) if value > 0]

            for neighbor in neighbors:
                new_vertex = neighbor
                new_path = path + [vertex]

                if new_vertex == goal:
                    return new_path + [goal]

                next_beam.append((new_vertex, new_path))


        next_beam.sort(key=lambda item: len(item[1]))


        current_beam = next_beam[:beam_width]

    return None


goal_vertex = 'G'
beam_width = 2 


start_vertex = vertices.index('S')
path_indices = beam_search(adjacency_matrix, start_vertex, vertices.index(goal_vertex), beam_width)

if path_indices is not None:

    path = [vertices[i] for i in path_indices]
    print("Path from 'S' to 'G' found by Beam Search:", " -> ".join(path))
else:
    print("No path from 'S' to 'G' found by Beam Search")


Path from 'S' to 'G' found by Beam Search: S -> A -> B -> G
